[package]
name = "custom-utils"
version = "0.1.0"
edition = "2021"
description = "Provide customized tools based on features"
repository = "https://github.com/jm-observer/custom-utils.git"

license-file = "LICENSE"
readme = "README.md"
exclude = [
    ".cargo_vcs_info.json",
]

[dependencies]


[features]

default = []

rustls = []

flexi-log = []

