[package]
name = "custom-utils"
version = "0.1.0"
edition = "2021"
description = "Provide customized tools based on features"
repository = "https://github.com/jm-observer/custom-utils.git"

license-file = "LICENSE"
readme = "README.md"

[dependencies]
anyhow = "1.0"
log = { version = "0.4", optional = true }
flexi_logger = { version = "0.22", optional = true }
time = {version = "0.3.7", features = ["macros"], optional = true}

[features]

default = []

develop = []
prod = []

rustls = []

logger = ["flexi_logger", "time", "log"]

[[example]]
name = "prod"
required-features = ["prod", "logger"]
[[example]]
name = "dev"
required-features = ["develop", "logger"]

