[package]
name = "custom-utils"
version = "0.1.0"
edition = "2021"
description = "Provide customized tools based on features"
repository = "https://github.com/jm-observer/custom-utils.git"

license-file = "LICENSE"
readme = "README.md"

[dependencies]
anyhow = "1.0"
#log = "0.4"
flexi_logger = { version = "0.22", optional = true }
time = {version = "0.3.7", features = ["macros"], optional = true}

[features]

default = []

develop = []
prod = []

rustls = []

log = ["flexi_logger", "time"]

[[example]]
name = "prod"
required-features = ["prod"]
[[example]]
name = "dev"
required-features = ["develop"]

