[package]
name = "custom-utils"
version = "0.1.0"
edition = "2021"
description = "Provide customized tools based on features"
repository = "https://github.com/jm-observer/custom-utils.git"

license-file = "LICENSE"
readme = "README.md"

[dependencies]
anyhow = "1.0"
log = { version = "0.4" }
flexi_logger = { version = "0.22", optional = true, features = ["use_chrono_for_offset"] }
time = {version = "0.3.7", features = ["macros"], optional = true}
tokio = {version ="1.18.0", features = ["signal", "rt-multi-thread", "macros", "time"]}

[target.'cfg(unix)'.dependencies]
libsystemd = {version ="0.5.0", optional = true}

[features]
default = []
dev = []
prod = []
rustls = []
logger = ["flexi_logger", "time"]
daemon = ["libsystemd"]

[[example]]
name = "prod"
required-features = ["prod", "logger", "daemon"]
[[example]]
name = "dev_win"
required-features = ["dev", "logger", "daemon"]
[[example]]
name = "dev_unix"
required-features = ["dev", "logger", "daemon"]

