# The run config is used for both run mode and debug mode

[[configs]]
name = "task"
program = "cargo"
args = ["clippy"]


[[configs]]
name = "task1"
program = "cargo"
args = ["run", "--example", "prod"]
